# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST  http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="Testiculartorsion.mp3"
Content-Type: audio/mpeg

< ./Testiculartorsion.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription

POST http://localhost:3333/videos/3ff198ba-09f2-441c-b027-6e276f829360/transcription
Content-Type: application/json

{
    "prompt": "Testicular"
}

###

# @name generate-ai-completion

POST http://localhost:3333/ai/complete
Content-Type: application/json

{
    "videoId": "3ff198ba-09f2-441c-b027-6e276f829360",
    "temperature": 0.5,
    "prompt": "Gere um resumo da transcrição do vídeo informada a seguir: ''' {transcription}'''"
}